const tenisNike = [
    {
        id: 1,
        numero: 41,
        nome: "Nike tenis",
        estilo: "Esportivo",
    },
    {
        id: 2,
        numero: 42,
        nome: "Nike Air Max 90",
        estilo: "Casual",
    },
    {
        id: 3,
        numero: 40,
        nome: "Nike Air Force 1",
        estilo: "Urbano",
    },
    {
        id: 4,
        numero: 43,
        nome: "Nike Revolution 5",
        estilo: "Corrida",
    },
    {
        id: 5,
        numero: 41,
        nome: "Nike SB Dunk Low",
        estilo: "Skate",
    },
    {
        id: 6,
        numero: 44,
        nome: "Nike Air Zoom Pegasus",
        estilo: "Corrida",
    },
    {
        id: 7,
        numero: 42,
        nome: "Nike Blazer Mid",
        estilo: "Casual",
    },
    {
        id: 8,
        numero: 40,
        nome: "Nike React Infinity Run",
        estilo: "Corrida",
    },
    {
        id: 9,
        numero: 43,
        nome: "Nike Air VaporMax",
        estilo: "Esportivo",
    },
    {
        id: 10,
        numero: 41,
        nome: "Nike Cortez",
        estilo: "Retro",
    },
    {
        id: 11,
        numero: 42,
        nome: "Nike Air Max 270",
        estilo: "Casual",
    },
    {
        id: 12,
        numero: 44,
        nome: "Nike Free RN",
        estilo: "Corrida",
    },
    {
        id: 13,
        numero: 40,
        nome: "Nike Air Zoom Structure",
        estilo: "Corrida",
    },
    {
        id: 14,
        numero: 43,
        nome: "Nike Air Max Plus",
        estilo: "Casual",
    },
    {
        id: 15,
        numero: 41,
        nome: "Nike Shox R4",
        estilo: "Esportivo",
    },
    {
        id: 16,
        numero: 42,
        nome: "Nike Air Max 97",
        estilo: "Casual",
    },
    {
        id: 17,
        numero: 44,
        nome: "Nike Air Zoom Vomero",
        estilo: "Corrida",
    },
    {
        id: 18,
        numero: 40,
        nome: "Nike Air Max 720",
        estilo: "Casual",
    },
    {
        id: 19,
        numero: 43,
        nome: "Nike SB Stefan Janoski",
        estilo: "Skate",
    },
    {
        id: 20,
        numero: 41,
        nome: "Nike Air Max 1",
        estilo: "Casual",
    },
    {
        id: 21,
        numero: 42,
        nome: "Nike Air Max 95",
        estilo: "Casual",
    },
    {
        id: 22,
        numero: 44,
        nome: "Nike Air Zoom Winflo",
        estilo: "Corrida",
    },
    {
        id: 23,
        numero: 40,
        nome: "Nike Air Max 200",
        estilo: "Casual",
    },
    {
        id: 24,
        numero: 43,
        nome: "Nike SB Blazer Low",
        estilo: "Skate",
    },
    {
        id: 25,
        numero: 41,
        nome: "Nike Air Max Tailwind",
        estilo: "Corrida",
    },
    {
        id: 26,
        numero: 42,
        nome: "Nike Air Max Sequent",
        estilo: "Corrida",
    },
    {
        id: 27,
        numero: 44,
        nome: "Nike Air Zoom Terra Kiger",
        estilo: "Trilha",
    },
    {
        id: 28,
        numero: 40,
        nome: "Nike Air Max Command",
        estilo: "Casual",
    },
    {
        id: 29,
        numero: 43,
        nome: "Nike SB Dunk High",
        estilo: "Skate",
    },
    {
        id: 30,
        numero: 41,
        nome: "Nike Air Max 98",
        estilo: "Casual",
    },
];

export default tenisNike;
